services:
  frontend:
    container_name: app_front
    build: ./frontend/rebu-front
    ports:
      - 80:80
    platform: linux/x86_64
    working_dir: /app-frontend
    environment:
      - API_BASE_URL=localhost:8080
    volumes:
      - ./frontend/rebu-front:/app-frontend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:80"]
      timeout: 10s
      retries: 5

  backend:
    container_name: app_backend
    build: ./backend/rebu-api
    ports:
      - 8080:8080
    platform: linux/x86_64
    working_dir: /app-backend
    depends_on:
      rebu-db:
        condition: service_healthy
    environment:
      - APP_PORT=8080
      - JWT_SECRET=jwt_secret
      # Os dados abaixo se referem ao container `db`
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_HOST=rebu-db
      - DB_PORT=5432
      - DB_NAME=rebu
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./backend/rebu-api:/app-backend
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:8080"]
      timeout: 10s
      retries: 5

  rebu-db:
    image: postgres:latest
    container_name: rebu-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: rebu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
